version: "3.8"

services:
  auto-feedback:
    build: .
    container_name: auto-feedback-app
    restart: unless-stopped
    ports:
      - "${FLASK_PORT:-5000}:5000"
      - "${STREAMLIT_PORT:-8501}:8501"
    environment:
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_DEBUG=${FLASK_DEBUG:-false}
      - STREAMLIT_HOST=0.0.0.0
      - STREAMLIT_PORT=8501
      - API_URL=http://localhost:5000
      - PYTHONUNBUFFERED=1
    volumes:
      - app-data:/app/data

volumes:
  app-data:
